Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/bansochain.gov.id/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"

  - &KemensosOrg
    Name: KemensosOrg
    ID: KemensosMSP
    MSPDir: crypto-config/peerOrganizations/kemensos.bansochain.gov.id/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('KemensosMSP.admin', 'KemensosMSP.peer', 'KemensosMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('KemensosMSP.admin', 'KemensosMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('KemensosMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('KemensosMSP.peer')"
    AnchorPeers:
      - Host: peer0.kemensos.bansochain.gov.id
        Port: 7051

  - &DinsosOrg
    Name: DinsosOrg
    ID: DinsosMSP
    MSPDir: crypto-config/peerOrganizations/dinsos.bansochain.gov.id/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('DinsosMSP.admin', 'DinsosMSP.peer', 'DinsosMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('DinsosMSP.admin', 'DinsosMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('DinsosMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('DinsosMSP.peer')"
    AnchorPeers:
      - Host: peer0.dinsos.bansochain.gov.id
        Port: 8051

  - &BankOrg
    Name: BankOrg
    ID: BankMSP
    MSPDir: crypto-config/peerOrganizations/bank.bansochain.gov.id/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('BankMSP.admin', 'BankMSP.peer', 'BankMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('BankMSP.admin', 'BankMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('BankMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('BankMSP.peer')"
    AnchorPeers:
      - Host: peer0.bank.bansochain.gov.id
        Port: 9051

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  Organizations:
  Policies:
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer.bansochain.gov.id:7050
  EtcdRaft:
    Consenters:
      - Host: orderer.bansochain.gov.id
        Port: 7050
        ClientTLSCert: crypto-config/ordererOrganizations/bansochain.gov.id/orderers/orderer.bansochain.gov.id/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/bansochain.gov.id/orderers/orderer.bansochain.gov.id/tls/server.crt
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  ThreeOrgsChannelGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities: *OrdererCapabilities
    Consortium: SampleConsortium
    Consortiums:
      SampleConsortium:
        Organizations:
          - *KemensosOrg
          - *DinsosOrg
          - *BankOrg
  
  BansosChannel:
    <<: *ChannelDefaults
    Consortium: SampleConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *KemensosOrg
        - *DinsosOrg
        - *BankOrg
      Capabilities: *ApplicationCapabilities
